# Generated by Django 5.1.3 on 2024-11-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJuegoDeTronos', '0002_character_house_season_delete_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='emblem',
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
