# Generated by Django 5.1.3 on 2024-11-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJuegoDeTronos', '0007_remove_character_seasons_character_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='seasons',
            field=models.ManyToManyField(to='appJuegoDeTronos.season'),
        ),
        migrations.AlterField(
            model_name='character',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='appJuegoDeTronos.house'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
