# Generated by Django 5.1.3 on 2024-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJuegoDeTronos', '0009_remove_character_image_character_is_alive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
    ]
